GMyBlog/GMyBlog/urls.py
import xadmin
from rest_framework.routers import DefaultRouter
from rest_framework.documentation import include_docs_urls

from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from blog.views import PostDetailView, IndexView, \
    CategoryView, TagView, SearchView, AuthorView
from blog.apis import PostViewSet, CategoryViewSet
from config.views import LinkListView
from comment.views import CommentView

# from .custom_site import custom_site
from .autocomplete import CategoryAutocomplete, TagAutocomplete  # StatusAutocomplete

router = DefaultRouter()
router.register(r'post', PostViewSet, basename='api-post')
router.register(r'category', CategoryViewSet, basename='api-category')

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', xadmin.site.urls, name='admin'),
    url(r'^super_admin/', admin.site.urls, name='super-admin'),
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
    url(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view(), name='tag-list'),
    url(r'^post/(?P<post_id>\d+).html/$', PostDetailView.as_view(), name='post-detail'),
    url(r'^links/$', LinkListView.as_view(), name='links'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^author/(?P<owner_id>\d+)/$', AuthorView.as_view(), name='author'),
    url(r'^comment/$', CommentView.as_view(), name='comment'),
    url(r'^category-autocomplete/$', CategoryAutocomplete.as_view(), name='category-autocomplete'),
    url(r'^tag-autocomplete/$', TagAutocomplete.as_view(), name='tag-autocomplete'),
    # url(r'^status-autocomplete/$', StatusAutocomplete.as_view(), name='status-autocomplete'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^api/post/', include(router.urls)),
    url(r'^api/docs/', include_docs_urls(title='myblog apis')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GMyBlog/comment/models.py
from django.db import models


class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEM = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    # target = models.ForeignKey(Post, verbose_name='评论目标')
    target = models.CharField(max_length=100, verbose_name='评论目标')
    content = models.CharField(max_length=200, verbose_name='内容')
    nickname = models.CharField(max_length=20, verbose_name='昵称')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEM,
                                         verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

    class Meta:
        verbose_name = verbose_name_plural = '评论'

GMyBlog/comment/forms.py
from django import forms
import mistune

from .models import Comment


class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=10,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': 'width: 60%;'}
        )
    )
    content = forms.CharField(
        label='内容',
        max_length=200,
        widget=forms.widgets.Textarea(
            attrs={'rows': 6, 'cols': 60, 'class': 'form-content'}
        )
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 10:
            raise forms.ValidationError('太短了~~~')
        content = mistune.markdown(content)
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'content']

GMyBlog/comment/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView

from .forms import CommentForm


class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            succeed = True
            return redirect(target)
        else:
            succeed = False

        context = {
            'succeed': succeed,
            'form': comment_form,
            'target': target,
        }
        return self.render_to_response(context)

GMyBlog/GMyBlog/themes/bootstrap/templates/comment/block.html
<hr>
<div class="comment">
    <form id="comment_form" class="form-group" action="/comment/" method="post">
        {% csrf_token %}
        <input type="hidden" name="target" value="{{ target }}">{{ comment_form }}
        <input type="submit" value="写好了">
    </form>
    <br>
    <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div class="nickname">
                {% autoescape off %}
                <span>{{ comment.created_time }}&nbsp;&nbsp;{{ comment.nickname }}:{{ comment.content}}</span>
                {% endautoescape %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

GMyBlog/GMyBlog/themes/bootstrap/templates/comment/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>
    <style>
        body {
            TEXT-ALIGN: center;
        }

        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }

        .errorlist {
            color: red;
        }

        ul li {
            list-style-type: none;
        }
    </style>
</head>
<body>
<div class="result">
    {% if succeed %}
    评论成功!
    <a href="{{ target }}">返回</a>
    {% else %}
    <ul class="errorlist">
        {% for field, message in form.errors.items %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    <a href="javascript:window.history.back();">返回</a>
    {% endif %}
</div>
</body>
</html>